AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Dynamo and Lambda Function with Maven
Globals:
  Api:
    EndpointConfiguration: REGIONAL
    BinaryMediaTypes:
        - "*/*"
Resources:
  LambdaDynamoMaven:
   Type: AWS::Serverless::Function
   Properties:
    Handler: com.saket.aws.lambdamvn.handler.PersonActionHandler::handleRequest
    Runtime: java8
    CodeUri: target/LambdaDynamoMaven-0.0.1-SNAPSHOT.jar
    MemorySize: 512
    Role: arn:aws:iam::323091370715:role/LambdaDynamoDbRole
    Timeout: 60
    Environment:
      Variables:
        DaxEndpoint: testdaxcluster.is5w0g.clustercfg.dax.use1.cache.amazonaws.com:8111
    Events:
     GetResource:
       Type: Api
       Properties:
         Path: /{proxy+}
         Method: any
Outputs:
  LambdaDynamoMavenFunc:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage'
    Export:
      Name: LambdaDynamoMavenFunction         